version: "3"
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DATABASE_NAME=zamoore_dev
      - DATABASE_USER=admin
